/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {

  static const String back1 = "assets/image/back1.png";
  static const String icon = "assets/image/icon.png";
  static const String loading = "assets/image/loading.gif";
}
